# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'CocoaMQTT'
  # Pods for IOT

  target 'IOTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
